# Generated by Django 4.0.6 on 2022-12-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_rename_profile_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='created_At',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
