# Generated by Django 4.0.6 on 2022-12-22 18:58

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_alter_user_profile_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('cost', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='post_images')),
                ('created_At', models.DateTimeField(default=datetime.datetime.now)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
