# Generated by Django 4.0.6 on 2022-12-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='User_Post',
        ),
    ]
