# Generated by Django 4.0.6 on 2022-12-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_rename_post_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
