# Generated by Django 4.0.6 on 2022-12-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0007_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='profileImg',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
    ]
