# Generated by Django 4.0.6 on 2022-12-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0011_remove_comment_post_id_comment_post_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
