# Generated by Django 4.0.6 on 2022-12-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0012_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
