# Generated by Django 4.0.6 on 2022-12-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0013_user_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
