# Generated by Django 4.0.6 on 2023-03-13 06:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0014_user_post_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profilePic',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
