# Generated by Django 4.0.6 on 2023-03-13 06:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0015_alter_user_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='profileImg',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
